ls:
  packages/@okta/vuepress-theme-prose:
    .vue: PascalCase
    .js: snake_case | point.case
    .scss: regex:?[a-zA-Z]+(_[a-zA-Z]+)* # regex for snake_case because for .scss shortname - 'snake_case' not working ¯\_(ツ)_/¯
    .dir: snake_case

ignore:
  - .git
  - node_modules
  - packages/@okta/vuepress-theme-prose/assets/fonts
